baseURL: 'https://oguz.lol'
languageCode: en-us
title: '~oguz'
theme: WonderMod

# Code Highlight
pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: monokai

params:
  env: production

  defaultTheme: dark
  
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  showtoc: true

  assets:
    disableHLJS: true

  homeInfoParams:
    Title: "Hi, \U0001F44B"
    Content: |
      Portefølje for 4.Semester.

      Her ses en overordnet plan for hver uge. Den kan dog variere uge for uge.

      | Mandag      | Tirsdag     | Onsdag  | Torsdag | Fredag                                 |
      | ----------- | ----------- | ------  | ------- | -------------------------------------- |
      | Projekt     | Flutter     | Laravel | Projekt | Flutter + Laravel og Afrunding af ugen |

  socialIcons:
    - name: GitHub
      url: "https://github.com/OguzHooz"
    - name: About
      url: 'about'

menu:
  main:
    - identifier: log
      name: Log
      url: log
      weight: 10
    - identifier: plan
      name: Plan
      url: plan
      weight: 20
    - identifier: source
      name: Sources
      url: source
      weight: 30
    - identifier: product
      name: Products
      url: product
      weight: 40
    - identifier: about
      name: About
      url: about
      weight: 50