baseURL: 'https://oguz.lol'
languageCode: en-us
title: '~oguz'
theme: WonderMod

# Code Highlight
pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: monokai

params:
  env: production

  defaultTheme: dark
  
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  showtoc: true

  assets:
    disableHLJS: true

  homeInfoParams:
    Title: "Hi, \U0001F44B"
    Content: |
      Her er min portefølje for 4. semester, hvor jeg vil dokumentere hele mit forløb med mine valgfag: webudvikling med Laravel og appudvikling med Flutter.
      
      Det vil blive ført en daglig log, som kan ses [her](/log), og de løbende læringsmål samt læringsplanen kan ses [her](/plan).

      Her ses en overordnet plan for hver uge. Den kan dog variere uge for uge.

      | Mandag      | Tirsdag     | Onsdag  | Torsdag | Fredag                                 |
      | ----------- | ----------- | ------  | ------- | -------------------------------------- |
      | Flutter     | Projekt     | Laravel | Projekt | Flutter + Laravel og afrunding af ugen |

  socialIcons:
    - name: GitHub
      url: "https://github.com/OguzHooz"

menu:
  main:
    - identifier: log
      name: Log
      url: log
      weight: 10
    - identifier: plan
      name: Plan
      url: plan
      weight: 20
    - identifier: source
      name: Kilder
      url: source
      weight: 30